version: '3.8'
services:
  db: 
    container_name: soccerapp-db
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5434:5432'
    volumes:
      - postgres:/var/lib/posgresql/data
    networks: 
      - app

  api:
    container_name: soccerapp-api
    build: .
    restart: always
    environment:
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
    ports:
     - "3333:3333"
    networks: 
      - app

networks:
  app:
    driver: bridge

volumes:
  postgres:
